<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb0da6eed9511452133f30fb82999a93f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PopupMaker\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PopupMaker\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitb0da6eed9511452133f30fb82999a93f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PopupMaker\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb0da6eed9511452133f30fb82999a93f', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PopupMaker\Vendor\Composer\Autoload\ComposerStaticInitb0da6eed9511452133f30fb82999a93f::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
